---
title: "Robustness Check with control of seasonality"
author: "Peng Sun"
date: "10/03/2022"
output:
  pdf_document: default
  html_document: default
---

```{r load packages, message=FALSE, warning=FALSE}
#Load packages
#install.packages("clubSandwich")
library(readr)
library(did)
library(fixest)
library(DRDID)
library(tidyverse)
library(plm)
library(stargazer)
library(sandwich)
library(lmtest)
library(jtools)
library(clubSandwich)
```

```{r,message=FALSE, warning=FALSE}
#read data
setwd("~/R")
df2012<-read_csv("~/R/df2012_20210920.csv")
```


# Robustness check with Control of seasonality (control of month dummy and quater dummy)
 
```{r}
# set levels of timedummy variables so that Y2012 will be used as 
names(df2012)
unique(df2012$timedummy)
```


```{r, message=FALSE, warning=FALSE}
df2012$timedummy<-fct_relevel(df2012$timedummy,levels="Y2012","Y2013","Y2014","Y2015","Y2016","Y2017","janapr18","t1","t2")
#set levels of groups dummies so that Group C will be used as base
df2012$groups<-fct_relevel(df2012$groups, levels="C","A","B","D")
# set levels of period dummies so that t0 period will be used as base
df2012$periods<-fct_relevel(df2012$periods, levels="t0","t1","t2")
df2012<-df2012%>%select(-1)
```

```{r}
df2012<-df2012 %>%
   mutate(timedummy2=case_when(year==2012~"Y2012",
                            year==2013~"Y2013",
                            year==2014~"Y2014",
                            year==2015~"Y2015",
                            year==2016~"Y2016",
                            year==2017~"Y2017",
                          janapr18==1~"Y2018janapr",
                            t1==1~"Yt1",
                            t2==1~"Yt2"))
unique(df2012$timedummy2)
```
```{r}
df2012$sale_date_splited<- strsplit(df2012$sale_date, "/")

df2012$sale_date_y<- sapply(df2012$sale_date_splited, function(x) x[[3]])


df2012$sale_date_m<- sapply(df2012$sale_date_splited, function(x) x[[2]])


df2012$sale_date_d<- sapply(df2012$sale_date_splited, function(x) x[[1]])

df2012 <- df2012 %>%
  mutate(sale_date_q = case_when(
    month %in% 1:3 ~ "Q1",
    month %in% 4:6 ~ "Q2",
    month %in% 7:9 ~ "Q3",
    month %in% 10:12 ~ "Q4"
  ))

date_new<-df2012$sale_date_splited
date_new<-lapply(date_new, function(x) as.Date(paste(x[3], x[2], x[1], sep = "-"), format = "%Y-%m-%d"))
#head(date_new)
df2012$sale_date_new<-date_new
```



## Create the imputated dataset (used in Col 2 and 4)
```{r}
# use the mean land_area and floor_area for imputation
mean(df2012$land_area, na.rm="true")
```
```{r}
mean(df2012$floor_area)
# only keep three significant figures
```

```{r}
df2012_mutated <-  df2012  
df2012_mutated$contour=replace_na(df2012_mutated$contour,"Unreported") 
df2012_mutated$deck=replace_na(df2012_mutated$deck,"Unreported")   
df2012_mutated$roof_material=replace_na(df2012_mutated$roof_material,"Unreported") 
df2012_mutated$wall_material=replace_na(df2012_mutated$wall_material,"Unreported") 
df2012_mutated$building_age=replace_na(df2012_mutated$building_age,"Unreported")
df2012_mutated$land_area=replace_na(df2012_mutated$land_area,0.069) 
df2012_mutated$floor_area=replace_na(df2012_mutated$floor_area,136) 
```

```{r}
garage=df2012_mutated$garages_mainroof
```

```{r}
# replace msising values with Unreported
garage[is.na(garage)]<-"Unreported"
```

```{r}
which(is.na(garage))
```
```{r}
df2012_mutated$garages_mainroof<-garage
```

 
```{r}
bedrooms_min=df2012_mutated$bedrooms_min
# replace msising values with Unreported
bedrooms_min[is.na(bedrooms_min)]<-"Unreported"
#head(bedrooms_min)
df2012_mutated$bedrooms_min<- bedrooms_min
```

```{r}
dim(df2012)
```

##  column 1
```{r}
#col1_q<-plm(lp~t1+t2+A+B+D+t1*A+t2*A+t1*B+t2*B+t1*D+t2*D+as.factor(sale_date_q), data=df2012, model="pooling", index=c("houseid","year") )
#summary(col1_q)
```
```{r}
col1_q<-feols(lp~t1+t2+A+B+D+t1*A+t2*A+t1*B+t2*B+t1*D+t2*D+as.factor(sale_date_q)|houseid+year, data=df2012 )
summary(col1_q)
```

 

```{r}
coefplot(col1_q,keep=c("t1:A","t2:A","t1:B","t2:B","t1:D","t2:D"), ylim=c(-0.4,0.4), axis.text.x = element_text(size=14))
```

```{r}
col1_m<-plm(lp~t1+t2+A+B+D+t1*A+t2*A+t1*B+t2*B+t1*D+t2*D+as.factor(sale_date_m),data=df2012, model="pooling", index=c("houseid","year") )
summary(col1_m)
```


```{r}
coefplot(col1_m,keep=c("t1:A","t2:A","t1:B","t2:B","t1:D","t2:D"), ylim=c(-0.4,0.4), axis.text.x = element_text(size=14))
```

## Column 2 
```{r}

col2_q<-lm(lp~t1+t2+t1*A+t2*A+t1*B+t2*B+t1*D+t2*D+as.factor(sale_date_q)+floor_area+land_area+bedrooms_min+as.factor(building_age)+ as.factor(deck)+ as.factor(wall_material) 
+as.factor(roof_material)+as.factor(garages_mainroof)+ as.factor(contour)+as.factor(timedummy2) +as.factor(suburb),data=df2012_mutated)
summary(col2_q)
```


```{r}
coefplot(col2_q,keep=c("t1:A","t2:A","t1:B","t2:B","t1:D","t2:D"), ylim=c(-0.4,0.4), axis.text.x = element_text(size=14))
```

```{r}

col2_m<-lm(lp~t1+t2+t1*A+t2*A+t1*B+t2*B+t1*D+t2*D+as.factor(sale_date_m)+floor_area+land_area+bedrooms_min+as.factor(building_age)+ as.factor(deck)+ as.factor(wall_material) 
+as.factor(roof_material)+as.factor(garages_mainroof)+ as.factor(contour)+as.factor(timedummy2) +as.factor(suburb),data=df2012_mutated)
summary(col2_q)
```


```{r}
coefplot(col2_m,keep=c("t1:A","t2:A","t1:B","t2:B","t1:D","t2:D"), ylim=c(-0.4,0.4), axis.text.x = element_text(size=14))
```
## Column 3 


```{r}
col3_q<-plm(lp~yr2012+yr2013+yr2014+yr2015+yr2016+yr2017+t1+t2+A+B+D+t1*A+t2*A+t1*B+t2*B+t1*D+t2*D+as.factor(sale_date_q),data=df2012, model="within",effect="individual", index=c("houseid","year"))
summary(col3_q)
```

```{r}
coefplot(col3_q,keep=c("t1:A","t2:A","t1:B","t2:B","t1:D","t2:D"), ylim=c(-0.4,0.4), axis.text.x = element_text(size=14))
```

```{r}
col3_m<-plm(lp~yr2012+yr2013+yr2014+yr2015+yr2016+yr2017+t1+t2+A+B+D+t1*A+t2*A+t1*B+t2*B+t1*D+t2*D+as.factor(sale_date_m),data=df2012, model="within",effect="individual", index=c("houseid","year"))
summary(col3_m)
```

```{r}
coefplot(col3_m,keep=c("t1:A","t2:A","t1:B","t2:B","t1:D","t2:D"), ylim=c(-0.4,0.4), axis.text.x = element_text(size=14))
```

## Column 4
```{r}
col4_q<-plm(lp~yr2012+yr2013+yr2014+yr2015+yr2016+yr2017+yr2012*A+yr2013*A+yr2014*A+yr2015*A+yr2016*A+yr2017*A+yr2012*B+yr2013*B+yr2014*B+yr2015*B+yr2016*B+yr2017*B+yr2012*D+yr2013*D+yr2014*D+yr2015*D+yr2016*D+yr2017*D+t1+t2+A+B+D+t1*A+t2*A+t1*B+t2*B+t1*D+t2*D++as.factor(sale_date_q)+floor_area+land_area+bedrooms_min+as.factor(building_age)+ as.factor(deck)+ as.factor(wall_material) 
+as.factor(roof_material)+as.factor(garages_mainroof)+ as.factor(contour)+as.factor(suburb),data=df2012_mutated,model="pooling", index=c("houseid","year"))
summary(col4_q)
```


```{r}
coefplot(col4_q,ylim=c(-0.4,0.4), keep=c("yr2012:A","yr2013:A","yr2014:A","yr2015:A","yr2016:A","yr2017:A","A:t1", "A:t2"), axis.text.x = element_text(size=14))
```

```{r}
coefplot(col4_q,keep=c("yr2012:B","yr2013:B","yr2014:B","yr2015:B","yr2016:B","yr2017:B", "B:t1","B:t2"), axis.text.x = element_text(size=14))
```
```{r}
coefplot(col4_q, keep=c("yr2012:D","yr2013:D","yr2014:D","yr2015:D","yr2016:D","yr2017:D", "D:t1", "D:t2"), axis.text.x = element_text(size=14))

```


```{r}
col4_m<-plm(lp~yr2012+yr2013+yr2014+yr2015+yr2016+yr2017+yr2012*A+yr2013*A+yr2014*A+yr2015*A+yr2016*A+yr2017*A+yr2012*B+yr2013*B+yr2014*B+yr2015*B+yr2016*B+yr2017*B+yr2012*D+yr2013*D+yr2014*D+yr2015*D+yr2016*D+yr2017*D+t1+t2+A+B+D+t1*A+t2*A+t1*B+t2*B+t1*D+t2*D++as.factor(sale_date_m)+floor_area+land_area+bedrooms_min+as.factor(building_age)+ as.factor(deck)+ as.factor(wall_material) 
+as.factor(roof_material)+as.factor(garages_mainroof)+ as.factor(contour)+as.factor(suburb),data=df2012_mutated,model="pooling", index=c("houseid","year"))
summary(col4_m)
```


```{r}
coefplot(col4_m,ylim=c(-0.4,0.4), keep=c("yr2012:A","yr2013:A","yr2014:A","yr2015:A","yr2016:A","yr2017:A","A:t1", "A:t2"), axis.text.x = element_text(size=14))
```

```{r}
coefplot(col4_m,keep=c("yr2012:B","yr2013:B","yr2014:B","yr2015:B","yr2016:B","yr2017:B", "B:t1","B:t2"), axis.text.x = element_text(size=14))
```
```{r}
coefplot(col4_m, keep=c("yr2012:D","yr2013:D","yr2014:D","yr2015:D","yr2016:D","yr2017:D", "D:t1", "D:t2"), axis.text.x = element_text(size=14))

```



## Column 5
```{r}
col5_q<-plm(lp~yr2012+yr2013+yr2014+yr2015+yr2016+yr2017+yr2012*A+yr2013*A+yr2014*A+yr2015*A+yr2016*A+yr2017*A+yr2012*B+yr2013*B+yr2014*B+yr2015*B+yr2016*B+yr2017*B+yr2012*D+yr2013*D+yr2014*D+yr2015*D+yr2016*D+yr2017*D+t1+t2+A+B+D+t1*A+t2*A+t1*B+t2*B+t1*D+t2*D++as.factor(sale_date_q)+floor_area+land_area+bedrooms_min+as.factor(building_age)+ as.factor(deck)+ as.factor(wall_material) 
+as.factor(roof_material)+as.factor(garages_mainroof)+ as.factor(contour)+as.factor(suburb),data=df2012_mutated,model="pooling", index=c("houseid","year"))
summary(col4_q)
```


```{r}
coefplot(col5_q,ylim=c(-0.4,0.4), keep=c("yr2012:A","yr2013:A","yr2014:A","yr2015:A","yr2016:A","yr2017:A","A:t1", "A:t2"), axis.text.x = element_text(size=14))
```

```{r}
coefplot(col5_q,keep=c("yr2012:B","yr2013:B","yr2014:B","yr2015:B","yr2016:B","yr2017:B", "B:t1","B:t2"), axis.text.x = element_text(size=14))
```
```{r}
coefplot(col5_q, keep=c("yr2012:D","yr2013:D","yr2014:D","yr2015:D","yr2016:D","yr2017:D", "D:t1", "D:t2"), axis.text.x = element_text(size=14))

```


```{r}
col5_m<-plm(lp~yr2012+yr2013+yr2014+yr2015+yr2016+yr2017+yr2012*A+yr2013*A+yr2014*A+yr2015*A+yr2016*A+yr2017*A+yr2012*B+yr2013*B+yr2014*B+yr2015*B+yr2016*B+yr2017*B+yr2012*D+yr2013*D+yr2014*D+yr2015*D+yr2016*D+yr2017*D+t1+t2+A+B+D+t1*A+t2*A+t1*B+t2*B+t1*D+t2*D++as.factor(sale_date_m)+floor_area+land_area+bedrooms_min+as.factor(building_age)+ as.factor(deck)+ as.factor(wall_material) 
+as.factor(roof_material)+as.factor(garages_mainroof)+ as.factor(contour)+as.factor(suburb),data=df2012_mutated,model="pooling", index=c("houseid","year"))
summary(col5_m)
```


```{r}
coefplot(col5_m,ylim=c(-0.4,0.4), keep=c("yr2012:A","yr2013:A","yr2014:A","yr2015:A","yr2016:A","yr2017:A","A:t1", "A:t2"), axis.text.x = element_text(size=14))
```

```{r}
coefplot(col5_m,keep=c("yr2012:B","yr2013:B","yr2014:B","yr2015:B","yr2016:B","yr2017:B", "B:t1","B:t2"), axis.text.x = element_text(size=14))
```
```{r}
coefplot(col5_m, keep=c("yr2012:D","yr2013:D","yr2014:D","yr2015:D","yr2016:D","yr2017:D", "D:t1", "D:t2"), axis.text.x = element_text(size=14))

```