---
title: "More robustness test"
author: "Peng"
date: "2023/3/10"
output:
  pdf_document: default
  html_document: default
---
```{r}
library(readr)
library(did)
library(fixest)
library(DRDID)
library(tidyverse)
library(plm)
library(stargazer)
library(sandwich)
library(lmtest)
library(jtools)
library(clubSandwich)
library(lubridate)
```


```{r}
setwd("~/R")
df2012<-read_csv("~/R/df2012_20210920_datefixed.csv")
```

```{r}
df2012$sale_date_splited<- strsplit(df2012$sale_date, "/")

df2012$sale_date_y<- sapply(df2012$sale_date_splited, function(x) x[[3]])


df2012$sale_date_m<- sapply(df2012$sale_date_splited, function(x) x[[2]])


df2012$sale_date_d<- sapply(df2012$sale_date_splited, function(x) x[[1]])

df2012 <- df2012 %>%
  mutate(sale_date_q = case_when(
    month %in% 1:3 ~ "Q1",
    month %in% 4:6 ~ "Q2",
    month %in% 7:9 ~ "Q3",
    month %in% 10:12 ~ "Q4"
  ))

date_new<-df2012$sale_date_splited
date_new<-lapply(date_new, function(x) as.Date(paste(x[3], x[2], x[1], sep = "-"), format = "%Y-%m-%d"))
head(date_new)
df2012$sale_date_new<-date_new

```

```{r}
df2012$timedummy<-fct_relevel(df2012$timedummy,levels="Y2012","Y2013","Y2014","Y2015","Y2016","Y2017","janapr18","t1","t2")
df2012$groups<-fct_relevel(df2012$groups, levels="C","A","B","D")
#set levels of groups dummies so that Group C will be used as base

df2012$groups_D<-fct_relevel(df2012$groups, levels="D","A","B","C")
#set levels of groups_D dummies so that Group C will be used as base

unique(df2012$groups)
# set levels of period dummies so that t0 period will be used as base
df2012$periods<-fct_relevel(df2012$periods, levels="t0","t1","t2")
```
```{r}
df2012$timedummy<-fct_relevel(df2012$timedummy,levels="Y2012","Y2013","Y2014","Y2015","Y2016","Y2017","janapr18","t1","t2")
```



```{r}
df2012<-df2012 %>%
   mutate(timedummy2=case_when(year==2012~"Y2012",
                            year==2013~"Y2013",
                            year==2014~"Y2014",
                            year==2015~"Y2015",
                            year==2016~"Y2016",
                            year==2017~"Y2017",
                          janapr18==1~"Y2018janapr",
                            t1==1~"Yt1",
                            t2==1~"Yt2"))
df2012<- df2012%>% 
  mutate(timedummy3=as.factor(yearqrt))
class(df2012$timedummy3)
unique(df2012$timedummy3)
unique(df2012$timedummy2)
df2012<-df2012%>%
  mutate(timedummy6= case_when(timedummy3=="2012 Q1"~ "Y2012Q1",
                             timedummy3=="2012 Q2"~ "Y2012Q2",
                             timedummy3=="2012 Q3"~ "Y2012Q3",
                             timedummy3=="2012 Q4"~ "Y2012Q4",
                             timedummy3=="2013 Q1"~ "Y2013Q1",
                             timedummy3=="2013 Q2"~ "Y2013Q2",
                             timedummy3=="2013 Q3"~ "Y2013Q3",
                             timedummy3=="2013 Q4"~ "Y2013Q4",
                             timedummy3=="2014 Q1"~ "Y2014Q1",
                             timedummy3=="2014 Q2"~ "Y2014Q2",
                             timedummy3=="2014 Q3"~ "Y2014Q3",
                             timedummy3=="2014 Q4"~ "Y2014Q4",
                             timedummy3=="2015 Q1"~ "Y2015Q1",
                             timedummy3=="2015 Q2"~ "Y2015Q2",
                             timedummy3=="2015 Q3"~ "Y2015Q3",
                             timedummy3=="2015 Q4"~ "Y2015Q4",
                             timedummy3=="2016 Q1"~ "Y2016Q1",
                             timedummy3=="2016 Q2"~ "Y2016Q2",
                             timedummy3=="2016 Q3"~ "Y2016Q3",
                             timedummy3=="2016 Q4"~ "Y2016Q4",
                             timedummy3=="2017 Q1"~ "Y2017Q1",
                             timedummy3=="2017 Q2"~ "Y2017Q2",
                             timedummy3=="2017 Q3"~ "Y2017Q3",
                             timedummy3=="2017 Q4"~ "Y2017Q4",
                             janapr18==1~"Y2018janapr",
                             t1==1~"Yt2",
                             t2==1~"Yt3"
                             ))
unique(df2012$timedummy6)
df2012$timedummy6<-fct_relevel(df2012$timedummy6, levels="Y2012Q1","Y2012Q2","Y2012Q3","Y2012Q4","Y2013Q1","Y2013Q2","Y2013Q3","Y2013Q4","Y2014Q1","Y2014Q2","Y2014Q3","Y2014Q4","Y2015Q1","Y2015Q2","Y2015Q3","Y2015Q4","Y2016Q1","Y2016Q2","Y2016Q3","Y2016Q4","Y2017Q1","Y2017Q2","Y2017Q3","Y2017Q4","Y2018janapr","Yt2","Yt3")
```



```{r}
df2012_mutated <-  df2012  
 df2012_mutated$contour=replace_na(df2012_mutated$contour,"Unreported") 
 df2012_mutated$deck=replace_na(df2012_mutated$deck,"Unreported")   
 # df2012_mutated$garages_mainroof=replace_na(df2012_mutated$garages_mainroof,"Unreported")  
 df2012_mutated$roof_material=replace_na(df2012_mutated$roof_material,"Unreported") 
 df2012_mutated$wall_material=replace_na(df2012_mutated$wall_material,"Unreported") 
 df2012_mutated$building_age=replace_na(df2012_mutated$building_age,"Unreported")
df2012_mutated$land_area=replace_na(df2012_mutated$land_area,0.069) 
df2012_mutated$floor_area=replace_na(df2012_mutated$floor_area,136) 
```


```{r}
garage=df2012_mutated$garages_mainroof

# replace msising values with Unreported
garage[is.na(garage)]<-"Unreported"

df2012_mutated$garages_mainroof<-garage
```

```{r}
bedrooms_min=df2012_mutated$bedrooms_min
# replace msising values with Unreported
bedrooms_min[is.na(bedrooms_min)]<-"Unreported"
#head(bedrooms_min)
df2012_mutated$bedrooms_min<- bedrooms_min
```

#column 1


```{r}
# add control of quarter dummy
col1_q<-feols(lp~t1+t2+A+B+D+t1*A+t2*A+t1*B+t2*B+t1*D+t2*D+as.factor(sale_date_q),data=df2012)
summary(col1_q)
```
```{r}
coefplot(col1_q,keep=c("t1:A","t2:A","t1:B","t2:B","t1:D","t2:D"), ylim=c(-0.4,0.4), axis.text.x = element_text(size=14))
```

```{r}
# add control of month dummy
col1_m<-feols(lp~t1+t2+A+B+D+t1*A+t2*A+t1*B+t2*B+t1*D+t2*D+as.factor(sale_date_m),data=df2012)
summary(col1_m)
```
```{r}

coefplot(col1_m,keep=c("t1:A","t2:A","t1:B","t2:B","t1:D","t2:D"), ylim=c(-0.4,0.4), axis.text.x = element_text(size=14))
```


# Column 2

```{r}
# add quarter dummy
col2_q<-feols(lp~t1+t2+t1*A+t2*A+t1*B+t2*B+t1*D+t2*D+as.factor(sale_date_q)+floor_area+land_area+bedrooms_min+as.factor(building_age)+ as.factor(deck)+ as.factor(wall_material) 
+as.factor(roof_material)+as.factor(garages_mainroof)+ as.factor(contour)+as.factor(timedummy2) +as.factor(suburb),data=df2012_mutated)
summary(col2_q)
```

```{r}
coefplot(col2_q,keep=c("t1:A","t2:A","t1:B","t2:B","t1:D","t2:D"), ylim=c(-0.4,0.4), axis.text.x = element_text(size=14))

```

```{r}
#add month dummy
col2_m<-feols(lp~t1+t2+t1*A+t2*A+t1*B+t2*B+t1*D+t2*D+as.factor(sale_date_m)+floor_area+land_area+bedrooms_min+as.factor(building_age)+ as.factor(deck)+ as.factor(wall_material) 
+as.factor(roof_material)+as.factor(garages_mainroof)+ as.factor(contour)+as.factor(timedummy2) +as.factor(suburb),data=df2012_mutated)
summary(col2_m)
```

```{r}
coefplot(col2_m,keep=c("t1:A","t2:A","t1:B","t2:B","t1:D","t2:D"), ylim=c(-0.4,0.4), axis.text.x = element_text(size=14))
```
#column 3

```{r}

# control quarter
col3_q<-feols(lp~yr2012+yr2013+yr2014+yr2015+yr2016+yr2017+t1+t2+A+B+D+t1*A+t2*A+t1*B+t2*B+t1*D+t2*D+as.factor(sale_date_q)|houseid+year, data=df2012)
summary(col3_q)
```

```{r}
coefplot(col3_q,keep=c("t1:A","t2:A","t1:B","t2:B","t1:D","t2:D"), ylim=c(-0.4,0.4), axis.text.x = element_text(size=14))
```
```{r}

# control month
col3_m<-feols(lp~yr2012+yr2013+yr2014+yr2015+yr2016+yr2017+t1+t2+A+B+D+t1*A+t2*A+t1*B+t2*B+t1*D+t2*D+as.factor(sale_date_m)|houseid+year, data=df2012)
summary(col3_m)
```
```{r}

coefplot(col3_m,keep=c("t1:A","t2:A","t1:B","t2:B","t1:D","t2:D"), ylim=c(-0.4,0.4), axis.text.x = element_text(size=14))

```


#Column 4

```{r}
#add quarter dummy
```

```{r}
col4_q<-feols(lp~yr2012+yr2013+yr2014+yr2015+yr2016+yr2017+yr2012*A+yr2013*A+yr2014*A+yr2015*A+yr2016*A+yr2017*A+yr2012*B+yr2013*B+yr2014*B+yr2015*B+yr2016*B+yr2017*B+yr2012*D+yr2013*D+yr2014*D+yr2015*D+yr2016*D+yr2017*D+t1+t2+A+B+D+t1*A+t2*A+t1*B+t2*B+t1*D+t2*D+floor_area+land_area+bedrooms_min+as.factor(building_age)+ as.factor(deck)+ as.factor(wall_material) 
+as.factor(roof_material)+as.factor(garages_mainroof)+ as.factor(contour)+as.factor(suburb)+as.factor(sale_date_q)|houseid+year,data=df2012_mutated)
summary(col4_q)
```
```{r}

coefplot(col4_q,keep=c("A:t1","A:t2","B:t1","B:t2","D:t1","D:t2"), ylim=c(-0.4,0.4), axis.text.x = element_text(size=14))
```


```{r}
# add month dummy
col4_m<-feols(lp~yr2012+yr2013+yr2014+yr2015+yr2016+yr2017+yr2012*A+yr2013*A+yr2014*A+yr2015*A+yr2016*A+yr2017*A+yr2012*B+yr2013*B+yr2014*B+yr2015*B+yr2016*B+yr2017*B+yr2012*D+yr2013*D+yr2014*D+yr2015*D+yr2016*D+yr2017*D+t1+t2+A+B+D+t1*A+t2*A+t1*B+t2*B+t1*D+t2*D+floor_area+land_area+bedrooms_min+as.factor(building_age)+ as.factor(deck)+ as.factor(wall_material) 
+as.factor(roof_material)+as.factor(garages_mainroof)+ as.factor(contour)+as.factor(suburb)+as.factor(sale_date_m)|houseid+year,data=df2012_mutated)
summary(col4_m)
```
```{r}

coefplot(col4_m,keep=c("A:t1","A:t2","B:t1","B:t2","D:t1","D:t2"), ylim=c(-0.4,0.4), axis.text.x = element_text(size=14))
```



```{r}
coefplot(col4_m,ylim=c(-0.4,0.4), keep=c("yr2012:A","yr2013:A","yr2014:A","yr2015:A","yr2016:A","yr2017:A","A:t1", "A:t2"), axis.text.x = element_text(size=14))
```

```{r}
coefplot(col4_m,keep=c("yr2012:B","yr2013:B","yr2014:B","yr2015:B","yr2016:B","yr2017:B", "B:t1","B:t2"), axis.text.x = element_text(size=14))
```
```{r}
coefplot(col4_m, keep=c("yr2012:D","yr2013:D","yr2014:D","yr2015:D","yr2016:D","yr2017:D", "D:t1", "D:t2"), axis.text.x = element_text(size=14))

```


# column 5

```{r}
# add quarter dummy
col5_q<-feols(lp~yr2012+yr2013+yr2014+yr2015+yr2016+yr2017+yr2012*A+yr2013*A+yr2014*A+yr2015*A+yr2016*A+yr2017*A+yr2012*B+yr2013*B+yr2014*B+yr2015*B+yr2016*B+yr2017*B+yr2012*D+yr2013*D+yr2014*D+yr2015*D+yr2016*D+yr2017*D+t1+t2+A+B+D+t1*A+t2*A+t1*B+t2*B+t1*D+t2*D+as.factor(sale_date_q)|houseid+year,data=df2012)
summary(col5_q)
```

```{r}
coefplot(col5_q,keep=c("A:t1","A:t2","B:t1","B:t2","D:t1","D:t2"), ylim=c(-0.4,0.4), axis.text.x = element_text(size=14))
```
```{r}
# add month dummy
col5_m<-feols(lp~yr2012+yr2013+yr2014+yr2015+yr2016+yr2017+yr2012*A+yr2013*A+yr2014*A+yr2015*A+yr2016*A+yr2017*A+yr2012*B+yr2013*B+yr2014*B+yr2015*B+yr2016*B+yr2017*B+yr2012*D+yr2013*D+yr2014*D+yr2015*D+yr2016*D+yr2017*D+t1+t2+A+B+D+t1*A+t2*A+t1*B+t2*B+t1*D+t2*D+as.factor(sale_date_m)|houseid+year,data=df2012)
summary(col5_m)
```
```{r}
coefplot(col5_m,keep=c("A:t1","A:t2","B:t1","B:t2","D:t1","D:t2"), ylim=c(-0.4,0.4), axis.text.x = element_text(size=14))
```




```{r}
coefplot(col5_m,ylim=c(-0.4,0.4), keep=c("yr2012:A","yr2013:A","yr2014:A","yr2015:A","yr2016:A","yr2017:A","A:t1", "A:t2"), axis.text.x = element_text(size=14))
```

```{r}
coefplot(col5_m,keep=c("yr2012:B","yr2013:B","yr2014:B","yr2015:B","yr2016:B","yr2017:B", "B:t1","B:t2"), axis.text.x = element_text(size=14))
```
```{r}
coefplot(col5_m, keep=c("yr2012:D","yr2013:D","yr2014:D","yr2015:D","yr2016:D","yr2017:D", "D:t1", "D:t2"), axis.text.x = element_text(size=14))

```

